bookshelf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shelves.urls", namespace="shelves")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


shelves/urls.py
from django.urls import path

from shelves.views import (
    index,
    AuthorListView,
    AuthorDetailView,
    AuthorCreateView,
    AuthorDeleteView,
    AuthorUpdateView,
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    PublicationListView,
    PublicationCreateView,
    PublicationUpdateView,
    PublicationDeleteView,
    GenreListView,
    GenreCreateView,
    GenreUpdateView,
    GenreDeleteView,
)

urlpatterns = [
    path("", index, name="index"),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
    path("authors/create", AuthorCreateView.as_view(), name="author-create"),
    path("authors/<int:pk>/delete", AuthorDeleteView.as_view(), name="author-delete"),
    path("authors/<int:pk>/update", AuthorUpdateView.as_view(), name="author-update"),

    path("books/", BookListView.as_view(), name="book-list"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/create", BookCreateView.as_view(), name="book-create"),
    path("books/<int:pk>/delete", BookDeleteView.as_view(), name="book-delete"),
    path("books/<int:pk>/update", BookUpdateView.as_view(), name="book-update"),

    path("publications/", PublicationListView.as_view(), name="publication-list"),
    path("publications/create", PublicationCreateView.as_view(), name="publication-create"),
    path("publications/<int:pk>/delete", PublicationDeleteView.as_view(), name="publication-delete"),
    path("publications/<int:pk>/update", PublicationUpdateView.as_view(), name="publication-update"),

    path("genres/", GenreListView.as_view(), name="genre-list"),
    path("genres/create", GenreCreateView.as_view(), name="genre-create"),
    path("genres/<int:pk>/delete", GenreDeleteView.as_view(), name="genre-delete"),
    path("genres/<int:pk>/update", GenreUpdateView.as_view(), name="genre-update"),

    path("accounts/profile/", index)
]

app_name = "shelves"

shelves/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Publication(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Genre(models.Model):
    genre = models.CharField(max_length=63)

    def __str__(self):
        return self.genre


class Author(AbstractUser):

    class Meta:
        verbose_name = "author"
        verbose_name_plural = "authors"


class Book(models.Model):
    title = models.CharField(max_length=255)
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    authors = models.ManyToManyField(Author, related_name="authors")
    price = models.IntegerField()

    def __str__(self):
        return f"{self.title}: {self.genre}"

shelves/forms.py
from django import forms
from django.contrib.auth import get_user_model

from shelves.models import Book


class BookSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"})
    )


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Book
        fields = "__all__"

shelves/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from shelves.forms import BookSearchForm, BookForm
from shelves.models import Author, Genre, Book, Publication


def index(request):
    num_authors = Author.objects.count()
    num_books = Book.objects.count()
    num_genres = Genre.objects.count()
    num_publication = Publication.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_authors": num_authors,
        "num_books": num_books,
        "num_genres": num_genres,
        "num_publication": num_publication,
        "num_visits": num_visits + 1,
    }

    return render(request, "shelves/index.html", context=context)


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 3


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    fields = "__all__"
    success_url = reverse_lazy("shelves:author-list")


class AuthorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Author
    fields = "__all__"
    success_url = reverse_lazy("shelves:author-list")


class AuthorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Author
    success_url = reverse_lazy("")


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "shelves/book_list.html"
    queryset = Book.objects.all()
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = BookSearchForm(initial=title)

        return context

    def get_queryset(self):
        title = self.request.GET.get("title")

        if title:
            return self.queryset.filter(username__icontains=title)

        return self.queryset


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy("shelves:book-list")
    template_name = "shelves/book_form.html"


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy("shelves:book-list")
    template_name = "shelves/book_form.html"


class BookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Author
    success_url = reverse_lazy("")


class GenreListView(LoginRequiredMixin, generic.ListView):
    model = Genre
    paginate_by = 3


class GenreCreateView(LoginRequiredMixin, generic.CreateView):
    model = Genre
    fields = "__all__"
    success_url = reverse_lazy("shelves:genre-list")
    template_name = "shelves/genre_form.html"


class GenreUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Genre
    fields = "__all__"
    success_url = reverse_lazy("shelves:genre-list")
    template_name = "shelves/genre_form.html"


class GenreDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Genre
    success_url = reverse_lazy("")


class PublicationListView(LoginRequiredMixin, generic.ListView):
    model = Publication
    paginate_by = 3


class PublicationCreateView(LoginRequiredMixin, generic.CreateView):
    model = Publication
    fields = "__all__"
    success_url = reverse_lazy("shelves:publication-list")
    template_name = "shelves/publication_form.html"


class PublicationUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Publication
    fields = "__all__"
    success_url = reverse_lazy("shelves:publication-list")
    template_name = "shelves/publication_form.html"


class PublicationDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Publication
    success_url = reverse_lazy("")

templates/base-presentation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <link rel="canonical" href="https://appseed.us/ui-kit/soft-ui-design-system"/>

  <title>
    Bookshelf - {% block title %}{% endblock %} | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="page-style" href="{% static 'css/soft-design-system.css' %}" rel="stylesheet" />

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="{% block body_class %}{% endblock body_class %}">

    {% include "includes/navigation.html" %}

    {% block content %}{% endblock content %}

    {% include "includes/footer.html" %}

    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <link rel="canonical" href="https://appseed.us/ui-kit/soft-ui-design-system"/>

  <title>
    Bookshelf - {% block title %}{% endblock %}
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="page-style" href="{% static 'css/soft-design-system.css' %}" rel="stylesheet" />

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="{% block body_class %}{% endblock body_class %}">
  <div style="padding-bottom: 7%">
    {% include "includes/navigation.html" %}
  </div>

    {% block content %}{% endblock content %}

    {% include "includes/footer.html" %}

    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/includes/footer.html

  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Bookshelf</h6>
          </div>
          <div>
            <h6 class="mt-3 mb-2 opacity-8">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim/" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://iradesign.io/" target="_blank">
                  Illustrations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/bits" target="_blank">
                  Bits & Snippets
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/affiliates/new" target="_blank">
                  Affiliate Program
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/contact-us" target="_blank">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center" target="_blank">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://services.creative-tim.com/?ref=ct-soft-ui-footer" target="_blank">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/sponsorships" target="_blank">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/terms" target="_blank">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/privacy" target="_blank">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/license" target="_blank">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Bookshelf &copy; <a target="_blank" href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a>
              - Coded by <a target="_blank" href="https://appseed.us" target="_blank">AppSeed</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
{% load static %}

<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'shelves:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'shelves:author-list' %}">All authors</a></li>
  <li class="list-group-item"><a href="{% url 'shelves:book-list' %}">All book</a></li>
  <li class="list-group-item"><a href="{% url 'shelves:genre-list' %}">All genres</a></li>
  <li class="list-group-item"><a href="{% url 'shelves:publication-list' %}">All publishing houses</a></li>
</ul>

templates/shelves/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete author?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/shelves/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ author.first_name }} {{ author.last_name }}
    <a href="{% url 'shelves:author-delete' pk=author.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'shelves:author-update' pk=author.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>

  <p><strong>First name:</strong> {{ author.first_name }}</p>
  <p><strong>Last name:</strong> {{ author.last_name }}</p>
  <p><strong>Is staff:</strong> {{ author.is_staff }}</p>

  <div class="ml-3">
    <h4>Books</h4>

    {% for book in author.books.all %}
        <hr>
        <p><strong>Title:</strong> {{ book.title }}</p>
        <p><strong>Publishing house:</strong> {{ book.pub_house.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{book.id}}</p>

    {% empty %}
      <p>No books!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/shelves/author_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} author</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/shelves/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <br><br><br><br><br><br><br><br><br><br>
  <h1>Delete book?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/shelves/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ book.title }}
    <a href="{% url 'shelves:book-delete' pk=book.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'shelves:book-update' pk=book.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Book: ({{ book.title }}, {{ book.genre.genre }}, {{ book.pub_house.name }})</p>
  <div>
  <h4>Authors</h4>

    {% for author in author.all %}
      <hr>
      <p><strong>First name:</strong> {{ author.first_name }}</p>
      <p><strong>Last name:</strong> {{ author.last_name }}</p>
      <p class="text-muted"><strong>Id:</strong> {{author.id}}</p>

    {% empty %}
      <p>No authors!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/shelves/book_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} book</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/shelves/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Book List
    <a style="float: right" href="{% url 'shelves:book-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
   <form action="" method="get" class="form-inline">
  {{ search_form.as_p }}
    <input class="btn btn-secondary" type="submit" value="🔍">
  </form>

  {% if book_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Genre</th>
        <th>Price</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for book in book_list %}
        <tr>
          <td>
            {{ book.id }}
          </td>
          <td>
            {{ book.title }}
          </td>
          <td>
            {{ book.genre.genre }}
          </td>
          <td>
            {{ book.price }}
          </td>
          <td>
            <a href="{% url 'shelves:book-update' pk=book.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
              href="{% url 'shelves:book-delete' pk=book.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no books in the bookshelf.</p>
  {% endif %}
{% endblock %}

templates/shelves/genre_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete genre?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/shelves/genre_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} genre</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/shelves/genre_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Genre List
    <a style="float: right" href="{% url 'shelves:genre-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if genre_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Genre</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for genre in genre_list %}
        <tr>
          <td>
            {{ genre.id }}
          </td>
          <td>
            {{ genre.genre }}
          </td>
          <td>
            <a href="{% url 'shelves:genre-update' pk=genre.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
              href="{% url 'shelves:genre-delete' pk=genre.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no genres in the bookshelf.</p>
  {% endif %}
{% endblock %}

templates/shelves/publication_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete publication?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/shelves/publication_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} publication</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/shelves/publication_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Publication List
    <a style="float: right" href="{% url 'shelves:publication-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if publication_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for publication in publication_list %}
        <tr>
          <td>
            {{ publication.id }}
          </td>
          <td>
            {{ publication.name }}
          </td>
          <td>
            <a href="{% url 'shelves:publication-update' pk=publication.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
              href="{% url 'shelves:publication-delete' pk=publication.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no publications in the bookshelf.</p>
  {% endif %}
{% endblock %}